# Generated by Django 3.2.20 on 2023-09-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
        ('users', '0002_auto_20230929_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rel_image_n_n',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_rel_image_n_n', to='camera.Image'),
        ),
    ]
